### ISSUE TITLE
Editing nodes after creation

### ISSUE THREAD

**Issue by BrydonLeonard** [BrydonLeonard/motivatr#5]
Need to be able to modify nodes after they've been added.
Could put the relocation controls into this menu as well.

**Comment by battesonb** [comment]
This would be great, could even create custom templates to save to your profile this way. So you can recreate common tasks that you need to track progress of.

**Comment by battesonb** [comment]
Commented on wrong issue, sorry.

**Comment by BrydonLeonard** [comment]
The only thing nodes store at the moment is their name, so you can now edit that on existing nodes.
