### ISSUE TITLE
Encoding trees as text

### ISSUE THREAD

**Issue by BrydonLeonard** [BrydonLeonard/motivatr#6]
Would be useful to have some way of exporting a tree as text so that someone else could create the tree easily on their side.

**Comment by battesonb** [comment]
This would be great, could even create custom templates to save to your profile this way. So you can recreate common tasks that you need to track progress of

**Comment by BrydonLeonard** [comment]
We could probably just write it as a Jason object and then minify it. Would save us making up some other way

**Comment by battesonb** [comment]
I agree, and it'd be easier putting it back into a js object directly and saving that.
